GET http://localhost:8080/devops_starter_war_exploded/api/xxx

###
POST http://localhost:8080/rest_day1_war_exploded/api/person
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"name": "Steve", "age": 25}


###
#ændring på id 4
PUT http://localhost:8080/rest_day1_war_exploded/api/person/4
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"name": "Steve", "age": 45}

